preco = 5.20
print(f"Preço: {preco:5.2f}")
print(f"Preço: {preco:10.2f}")
print(f"Preço: R${preco:.2f}")
print(f"Preço: R${preco:^10.2f}")
print(f"Preço: R${preco:>10.2f}")
print(f"Preço: R${preco:<10.2f}")
print(f"Preço: R${preco:.^10.2f}")
print(f"Preço: R${preco:x^10.2f}")
print(f"Preço: R${preco:_^10.2f}")
print(f"\nPreço: R${preco * 10:5.2f}")
print("\nE pode ser encontrado nas melhores lojas do ramo\n")
print(f"""""")